# Generated by Django 4.0.5 on 2022-06-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_alter_vacancy_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='timestamp',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
